services:
  concept-graphs-api:
    build: .
    image: concept-graphs-api
    restart: unless-stopped
    ports:
      - 9007:9007
    volumes:
      - results:/rest_api/tmp
      - .:/rest_api

volumes:
  results:
