services:
  concept-graphs-api:
    image: ghcr.io/onto-med/concept-graphs/concept-graphs-api:1.0.1
    restart: unless-stopped
    ports:
      - 9007:9007
    volumes:
      - results:/rest_api/tmp
      - venv:/rest_api/.venv
      - cache:/root/.cache
    networks:
      - concept-graphs-network

volumes:
  results:
  venv:
  cache:

networks:
  concept-graphs-network:
    external: true
    name: concept-graphs-network
