services:
  concept-graphs-api:
    image: ghcr.io/onto-med/concept-graphs/concept-graphs-api:1.0.0
    restart: unless-stopped
    ports:
      - 9007:9007
    volumes:
      - results:/rest_api/tmp
    networks:
      - concept-graphs-network

volumes:
  results:

networks:
  concept-graphs-network:
    external: true
    name: concept-graphs-network
