"""Pydantic data models for query expansion.

The query-expansion workflow is intentionally modeled in three stages:

1. A request describes the input term, requested semantic categories, LLM
   settings, and optional grounding sources.
2. The LLM returns an ``ExpansionGeneration`` containing raw generated
   candidates.
3. The service grounds those candidates against terminology/ontology sources and
   returns a ``QueryExpansionResponse`` with evidence and grounding status.

The models are Pydantic/PydanticAI-friendly: ``ExpansionGeneration`` can be used
as a structured output model for a PydanticAI agent while the rest of the package
remains importable without PydanticAI installed.
"""

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field, field_validator

from src.query_expansion.categories import (
    DEFAULT_EXPANSION_CATEGORIES,
    ExpansionCategory,
)


class GroundingStatus(StrEnum):
    """How well an LLM-generated candidate is supported by external sources."""

    GROUNDED = "grounded"
    """The candidate is supported by at least one source above the score threshold."""

    PARTIALLY_GROUNDED = "partially_grounded"
    """Reserved for future source adapters that can provide weaker relation evidence."""

    LLM_ONLY = "llm_only"
    """The candidate was generated by the LLM but not found in configured sources."""

    REJECTED = "rejected"
    """The candidate failed grounding criteria and is omitted from normal responses."""


class SourceConfig(BaseModel):
    """Configuration for a grounding source.

    A source is an ontology, terminology, dictionary, or API that can validate or
    enrich LLM-generated candidates. Currently only ``type="local"`` is
    implemented.
    """

    name: str = Field(description="Human-readable source name used in evidence.")
    type: str = Field(default="local", description="Source adapter type.")
    path: str | None = Field(
        default=None, description="Path for local YAML/JSON terminology sources."
    )
    url: str | None = Field(
        default=None, description="Base URL for future HTTP/API-backed sources."
    )
    options: dict[str, Any] = Field(
        default_factory=dict, description="Adapter-specific source options."
    )


class GroundingOptions(BaseModel):
    """Options controlling how generated candidates are filtered after grounding."""

    include_llm_only: bool = Field(
        default=True,
        description="Include candidates that are not grounded in any configured source.",
    )
    minimum_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
        description="Minimum grounding score required to treat a candidate as grounded.",
    )
    reject_below_minimum: bool = Field(
        default=False,
        description="Drop candidates below minimum_score instead of returning them as llm_only.",
    )


class LLMConfig(BaseModel):
    """Configuration for the LLM used as primary expansion generator.

    The ``model`` value is passed to the selected LLM generator. Provider-specific
    parameters can be passed through ``options``. For the LangChain generator,
    ``options.provider`` currently supports ``ollama``, ``openai``, and
    ``blablador``.
    """

    model: str = Field(description="LLM model identifier for the selected generator.")
    system_prompt: str | None = Field(
        default=None, description="Optional system prompt for the expansion agent."
    )
    instructions: str | None = Field(
        default=None,
        description="Reserved for additional user/deployment instructions.",
    )
    options: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional provider/generator-specific keyword arguments.",
    )


class QueryExpansionRequest(BaseModel):
    """Input request for LLM-first, source-grounded query expansion."""

    term: str = Field(
        min_length=1, description="Input term to expand, e.g. 'myocardial infarction'."
    )
    language: str = Field(
        default="en", description="Language code used for prompting and source lookup."
    )
    categories: list[ExpansionCategory] = Field(
        default_factory=lambda: list(DEFAULT_EXPANSION_CATEGORIES),
        description="Semantic expansion categories requested from the LLM.",
    )
    limit_per_category: int = Field(
        default=10,
        ge=1,
        le=100,
        description="Maximum number of generated candidates per category.",
    )
    llm: LLMConfig = Field(description="Required LLM generator configuration.")
    sources: list[SourceConfig] = Field(
        default_factory=list,
        description="Optional sources used to ground/validate generated candidates.",
    )
    grounding: GroundingOptions = Field(
        default_factory=GroundingOptions,
        description="Grounding and post-filtering behavior.",
    )

    @field_validator("term")
    @classmethod
    def strip_term(cls, value: str) -> str:
        """Normalize accidental surrounding whitespace in the input term."""
        return value.strip()


class GeneratedExpansionCandidate(BaseModel):
    """Raw candidate produced by the LLM before grounding.

    ``rationale`` is the LLM's short explanation for why the candidate belongs to
    the category. It is not used as proof. It is carried through to the response
    to support debugging, review, or UI display.
    """

    term: str = Field(
        min_length=1,
        description="Generated expansion term, e.g. 'heart attack' or 'aspirin'.",
    )
    category: ExpansionCategory = Field(
        description="Semantic category assigned by the LLM."
    )
    rationale: str | None = Field(
        default=None,
        description="Optional LLM explanation for the candidate/category choice; not grounding evidence.",
    )

    @field_validator("term")
    @classmethod
    def strip_candidate_term(cls, value: str) -> str:
        """Normalize accidental surrounding whitespace in generated candidates."""
        return value.strip()


class ExpansionGeneration(BaseModel):
    """Structured LLM output model for PydanticAI.

    A PydanticAI agent should return this object. The service will then ground
    each candidate against configured sources.
    """

    candidates: list[GeneratedExpansionCandidate] = Field(
        default_factory=list, description="LLM-generated expansion candidates."
    )


class GroundingEvidence(BaseModel):
    """Evidence that a source supports an expansion candidate."""

    source: str = Field(description="Name of the source that produced the evidence.")
    matched_term: str = Field(
        description="Source term/synonym that matched the generated candidate."
    )
    score: float = Field(
        ge=0.0,
        le=1.0,
        description="Grounding confidence score assigned by the source adapter.",
    )
    relation: str | None = Field(
        default=None,
        description="Source relation type, e.g. exact_or_synonym, broader, narrower.",
    )
    source_id: str | None = Field(
        default=None, description="Optional concept/code identifier from the source."
    )
    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Additional source-specific evidence metadata.",
    )


class GroundedExpansionCandidate(BaseModel):
    """Final expansion candidate after grounding and filtering."""

    term: str = Field(description="Expansion term returned to the caller.")
    category: ExpansionCategory = Field(description="Semantic expansion category.")
    status: GroundingStatus = Field(description="Grounding classification.")
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Highest grounding evidence score, or 0 for ungrounded LLM-only terms.",
    )
    evidence: list[GroundingEvidence] = Field(
        default_factory=list, description="Source evidence supporting the candidate."
    )
    rationale: str | None = Field(
        default=None,
        description="Optional LLM rationale copied from the generated candidate.",
    )


class QueryExpansionResponse(BaseModel):
    """Response returned by the query-expansion service/API."""

    term: str = Field(description="Original input term.")
    language: str = Field(description="Request language.")
    expansions: dict[ExpansionCategory, list[GroundedExpansionCandidate]] = Field(
        description="Expansion candidates grouped by requested category."
    )
