# Name of the corpus; can be chosen freely (but acts as reference point between the different endpoint actions)
corpus_name: default
# (for German: Sahajtomar/German-semantic; English: sentence-transformers/paraphrase-albert-small-v2)
model: Sahajtomar/German-semantic
# Number of processes that will be spawned (how many cores will be utilized)
n_process: 1
# ...
storage_method: "vectorstore"
vectorstore_normalizeEmbeddings: false
vectorstore_annParameters:
  spaceType: "dotproduct"
  parameters:
      efConstruction: 1024
      m: 16
# With the prefix 'scaling_' you can tune the various parameters for the 'down_scale_algorithm' if desired
#scaling_*